name: 'GitHub Actions Version Updater'
on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.7.1
